include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
  errors:
    # informazioni di stile non bloccanti
    deprecated_member_use: info
    use_build_context_synchronously: warning

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: true
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false
